###### Config

baseurl = "https://solus-project.com/"
title = "Solus"

###### Content
archetypedir = "themes/solus/archetypes"
buildDrafts = false
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
googleanalytics = "UA-Not-Yet"
metaDataFormat = "toml"
paginate = 5
layoutsdir =   "themes/solus/layouts"
theme = "solus"

###### Special Params

[params]
	category = ["budgie", "infrastructure", "news", "packages", "partners", "plans", "releases", "security", "twis"]
	copyright = "2017"
	footermenu = ["solus", "social", "support", "pressmenu"] # Because I can't for the life of me get Hugo nested lists to work
	userguide = "https://drive.google.com/open?id=0B5Ymf8oYXx-PUFk4UG1WOFRnTzQ"

[params.menus]
	main = [ "home", "blog", "download", "support_us", "help", "budgie", "store", "press"]
	footer = [ "solus", "social", "support", "press"]
	solus = [ "download" ]
	social = [ "facebook", "google_plus", "reddit", "twitter"]
	support = ["dev_tracker", "forums", "google_plus_community", "help_center", "irc"]
	press = ["press_center", "branding"]

[params.menuurls]
	home = "home"
	blog = "blog"
	branding = "branding"
	budgie = "budgie"
	dev_tracker = "https://dev.solus-project.com"
	download = "download"
	facebook = "https://facebook.com/get.solus"
	forums = "https://solus-project.com/forums"
	google_plus = "https://plus.google.com/u/0/+Solus-Project"
	google_plus_community = "https://plus.google.com/communities/104830131595272878110"
	help = "help-center/home"
	help_center = "help-center/home"
	irc = "irc://irc.freenode.net/#Solus"
	press = "press-center"
	press_center = "press-center"
	reddit = "https://reddit.com/r/SolusProject"
	store = "http://www.unixstickers.com/stickers/software_stickers/solus-linux-shaped-sticker"
	support_us = "support"
	twitter = "https://twitter.com/SolusProject"

###### Blackfriday Markdown Tweaks

[blackfriday]
	extensions = ["fencedCodeBlocks"]
	hrefTargetBlank = true # Opens external URLs in a new tab / window (target _blank)

###### Languages

[languages.en]
Title = "English"
Weight = 1

[languages.sr]
Title = "Serbian"
Weight = 2