---
# Config
baseurl: "https://solus-project.com/"
config: "config.yaml"
title: "Solus"
# Content
archetypedir: "themes/solus/archetypes"
languageCode: "en-us"
metaDataFormat: "yaml"
paginate: 5
layoutsdir:   "themes/solus/layouts"
# Blackfriday Markdown Tweaks
blackfriday:
    hrefTargetBlank: true # Opens external URLs in a new tab / window (target _blank)
# Menu
menu:
    main:
        - Name: "Home"
          Identifier: "home"
          URL: "/"
        - Name: "Blog"
          Identifier: "blog"
          URL: "/blog"
        - Name: "Download"
          Identifier: "download"
          URL: "/download"
        - Name: "Support Us"
          Identifier: "support-us"
          URL: "/support-us"
        - Name: "Solus"
          Identifier: "solus_page"
          URL: "/solus"
        - Name: "Budgie"
          Identifier: "budgie"
          URL: "/budgie"
        - Name: "Press"
          Identifier: "press"
          URL: "/press"
    footer:
        - Identifier: "footer"
    solusMenu:
        - Identifier: "solus-menu"
        - Parent: "footer"
        - Name: "Overview"
          Identifier: "overview"
          URL: "/solus"
        - Name: "Download"
          Identifier: "download"
          URL: "/download"
        - Name: "Technical Specifications"
          Identifier: "technical_specifications"
          URL: "/solus/technical-specifications"
    communityMenu:
        - Identifier: "community-menu"
        - Parent: "footer"
        - Name: "Facebook"
          Identifier: "facebook"
          URL: "https://facebook.com/get.solus"
        - Name: "Google+"
          Identifier: "google_plus"
          URL: "https://plus.google.com/u/0/+Solus-Project"
        - Name: "Reddit"
          Identifier: "reddit"
          URL: "https://reddit.com/SolusProject"
        - Name: "Twitter"
          Identifier: "twitter"
          URL: "https://twitter.com/SolusProject"
    supportMenu:
        - Identifier: "support-menu"
        - Parent: "footer"
        - Name: "Bug Tracker"
          Identifier: "bug_tracker"
          URL: "https://bugs.solus-project.com"
        - Name: "Documentation"
          Identifier: "documentation"
          URL: "https://wiki.solus-project.com"
        - Name: "Forums"
          Identifier: "forums"
          URL: "https://solus-project.com/forums"
        - Name: "Google+ Community"
          Identifier: "google_plus_community"
          URL: "https://plus.google.com/communities/104830131595272878110"
        - Name: "IRC"
          Identifier: "irc"
          URL: "irc://irc.freenode.net/#Solus"
# Special Params
params:
    blogCategories: ["budgie", "news", "packages", "plans", "releases", "security", "twis"]
    copyrightYears: "2015-2016"
    imgdir: "https://solus-project.com/imgs/"
    jsdir: "https://solus-project.com/js/"
    users:
        - Name: "Ikey Doherty"
          Identifier: "ikey"
          Role: "Solus Project Founder and Lead Developer"
        - Name: "Justin Zobel"
          Identifier: "justin"
          Role: "Solus Project Community Manager"
        - Name: "Joshua Strobl"
          Identifier: "joshua"
          Role: "Solus Project Communications Managers"
# Theming
themesDir: "themes"
theme: "solus"
---
