###### Config

baseurl = "https://getsol.us/"
title = "Solus"

###### Content
archetypedir = "themes/solus/archetypes"
buildDrafts = false
buildFuture = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
googleanalytics = "UA-Not-Yet"
metaDataFormat = "toml"
paginate = 5
layoutsdir =   "themes/solus/layouts"
theme = "solus"

###### Special Params

[params]
	domain = "getsol.us"
	category = ["budgie", "infrastructure", "news", "packages", "partners", "plans", "releases", "security", "roundup", "twis"]
	copyright = "2020"
	footermenu = ["solus", "social", "support", "pressmenu"] # Because I can't for the life of me get Hugo nested lists to work
	userguide = "https://drive.google.com/open?id=0B5Ymf8oYXx-PUFk4UG1WOFRnTzQ"

[params.menus]
	main = [ "home", "about", "blog", "download", "help_center", "forum", "get_involved"]
	footer = [ "solus", "social", "support", "press"]
	solus = [ "about", "download", "experiences", "roadmap", "team", "technologies" ]
	social = [ "facebook", "mastodon", "reddit", "twitter", "twitch"]
	support = ["dev_tracker", "forums", "help_center", "irc"]
	press = ["press_center", "branding"]

[params.menuurls]
	about = "/solus/about"
	home = "home"
	blog = "blog"
	branding = "branding"
	budgie = "budgie"
	dev_tracker = "https://dev.getsol.us"
	download = "download"
	experiences = "/solus/experiences"
	facebook = "https://facebook.com/get.solus"
	forum = "https://discuss.getsol.us"
	forums = "https://discuss.getsol.us"
	get_involved = "/articles/contributing/getting-involved/en/"
	help_center = "help-center/home"
	irc = "/articles/contributing/getting-involved/en/#irc"
	mastodon = "https://fosstodon.org/@Solus"
	press = "press-center"
	press_center = "press-center"
	reddit = "https://www.reddit.com/r/SolusProject"
	roadmap = "/solus/roadmap"
	support_us = "/articles/contributing/getting-involved/en/"
	team = "/solus/team"
	technologies = "/solus/technologies"
	twitter = "https://twitter.com/SolusProject"
	twitch = "https://twitch.tv/getsolus"

[params.teams]
	core = ["bryan", "joshua"]
	global = ["friedrich", "joe", "pierre", "rune"]