---
# Config
baseurl: "https://solus-project.com/"
config: "config.yaml"
title: "Solus"
# Content
archetypedir: "themes/solus/archetypes"
buildDrafts: true
languageCode: "en-us"
metaDataFormat: "yaml"
paginate: 2
layoutsdir:   "themes/solus/layouts"
# Blackfriday Markdown Tweaks
blackfriday:
    hrefTargetBlank: true # Opens external URLs in a new tab / window (target _blank)
# Menu
menu:
  main:
      - Name: "Home"
        Identifier: "home"
        URL: "/"
      - Name: "Blog"
        Identifier: "blog"
        URL: "/blog"
      - Name: "Download"
        Identifier: "download"
        URL: "/download"
      - Name: "Support Us"
        Identifier: "support-us"
        URL: "/support-us"
      - Name: "Solus"
        Identifier: "solus-page"
        URL: "/solus"
      - Name: "Budgie"
        Identifier: "budgie"
        URL: "/budgie"
      - Name: "Press"
        Identifier: "press"
        URL: "/press"
  solus:
      - Identifier: "solus"
      - Name: "Overview"
        Identifier: "overview"
        URL: "/solus"
      - Name: "Download"
        Identifier: "download"
        URL: "/download"
      - Name: "Technical Specifications"
        Identifier: "technical-specifications"
        URL: "/solus/technical-specifications"
  community:
      - Identifier: "community"
      - Name: "Facebook"
        Identifier: "facebook"
        URL: "https://facebook.com/get.solus"
      - Name: "Google+"
        Identifier: "google_plus"
        URL: "https://plus.google.com/u/0/+Solus-Project"
      - Name: "Reddit"
        Identifier: "reddit"
        URL: "https://reddit.com/SolusProject"
      - Name: "Twitter"
        Identifier: "twitter"
        URL: "https://twitter.com/SolusProject"
  support:
      - Identifier: "support"
      - Name: "Bug Tracker"
        Identifier: "bug_tracker"
        URL: "https://bugs.solus-project.com"
      - Name: "Documentation"
        Identifier: "documentation"
        URL: "https://wiki.solus-project.com"
      - Name: "Forums"
        Identifier: "forums"
        URL: "https://solus-project.com/forums"
      - Name: "Google+ Community"
        Identifier: "google_plus_community"
        URL: "https://plus.google.com/communities/104830131595272878110"
      - Name: "IRC"
        Identifier: "irc"
        URL: "irc://irc.freenode.net/#Solus"
# Special Params
params:
    # Because I can't for the life of me get Hugo nested lists to work
    footermenu: ["solus", "community", "support"]
    copyright: "2016"
# Taxonomies
    category: ["budgie", "news", "packages", "plans", "releases", "security", "twis"]
# Theming
themesDir: "themes"
theme: "solus"
---
