---
# Config
baseurl: "https://solus-project.com/"
config: "config.yaml"
title: "Solus"
# Content
archetypedir: "themes/solus/archetypes"
buildDrafts: true
googleanalytics: "UA-Not-Yet"
languageCode: "en-us"
metaDataFormat: "yaml"
paginate: 5
layoutsdir:   "themes/solus/layouts"
# Blackfriday Markdown Tweaks
blackfriday:
    hrefTargetBlank: true # Opens external URLs in a new tab / window (target _blank)
# Menu
menu:
  main:
      - Name: "Home"
        Identifier: "home"
        URL: "/home"
        Weight: 1
      - Name: "Blog"
        Identifier: "blog"
        URL: "/blog"
        Weight: 2
      - Name: "Download"
        Identifier: "download"
        URL: "/download"
        Weight: 3
      - Name: "Support Us"
        Identifier: "support-us"
        URL: "/support"
        Weight: 4
      - Name: "Budgie"
        Identifier: "budgie"
        URL: "/budgie"
        Weight: 5
      - Name: "Store"
        Identifier: "store"
        URL: "http://www.unixstickers.com/stickers/software_stickers/solus-linux-shaped-sticker"
        Weight: 6
      - Name: "Press"
        Identifier: "presslink"
        URL: "/press-centre"
        Weight: 7
  solus:
      - Identifier: "solus"
      - Name: "Download"
        Identifier: "download"
        URL: "/download"
        Weight: 1
  social:
      - Identifier: "social"
      - Name: "Facebook"
        Identifier: "facebook"
        URL: "https://facebook.com/get.solus"
        Weight: 1
      - Name: "Google+"
        Identifier: "google_plus"
        URL: "https://plus.google.com/u/0/+Solus-Project"
        Weight: 2
      - Name: "Reddit"
        Identifier: "reddit"
        URL: "https://reddit.com/r/SolusProject"
        Weight: 3
      - Name: "Twitter"
        Identifier: "twitter"
        URL: "https://twitter.com/SolusProject"
        Weight: 4
  support:
      - Identifier: "support"
      - Name: "Dev Tracker"
        Identifier: "dev_tracker"
        URL: "https://dev.solus-project.com"
        Weight: 1
      - Name: "Documentation"
        Identifier: "documentation"
        URL: "https://wiki.solus-project.com"
        Weight: 2
      - Name: "Forums"
        Identifier: "forums"
        URL: "https://solus-project.com/forums"
        Weight: 3
      - Name: "Google+ Community"
        Identifier: "google_plus_community"
        URL: "https://plus.google.com/communities/104830131595272878110"
        Weight: 4
      - Name: "IRC"
        Identifier: "irc"
        URL: "irc://irc.freenode.net/#Solus"
        Weight: 5
  pressmenu:
      - Identifier: "pressmenu"
      - Name: "Press Centre"
        Identifier: "pressfooteritem"
        URL: "/press-centre"
        Weight: 1
      - Name: "Branding Guidelines"
        Identifier: "brandingguidelines"
        URL: "/branding-guidelines"
        Weight: 2
# Special Params
params:
    copyright: "2016"
    # Because I can't for the life of me get Hugo nested lists to work
    footermenu: ["solus", "social", "support", "pressmenu"]
    userguide: "https://drive.google.com/open?id=0B5Ymf8oYXx-PUFk4UG1WOFRnTzQ"
# Taxonomies
    category: ["budgie", "infrastructure", "news", "packages", "partners", "plans", "releases", "security", "twis"]
# Theming
themesDir: "themes"
theme: "solus"
---
