# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Solus"
license = "GPL-2.0"
licenselink = "No no no, no link for you."
description = "Solus Site theme"
homepage = "https://solus-project.com/"
tags = ["solus" ]
features = ["being amazeballs"]
min_version = 0.15

[author]
  name = "Solus Project"
  homepage = "https://solus-project.com"
